### ISSUE TITLE
Docker image for aarch64

### ISSUE THREAD

**Issue by Kirill** [zws-im/zws#263]
Please create docker image for aarch64 architecture.
For now I see 
```
api_1         | standard_init_linux.go:228: exec user process caused: exec format error
api_1         | standard_init_linux.go:228: exec user process caused: exec format error
api_1         | standard_init_linux.go:228: exec user process caused: exec format error
api_1         | standard_init_linux.go:228: exec user process caused: exec format error
api_1         | standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by Kirill** [comment]
That's great quick... Thank you. Wait next version.

**Comment by jonahsnider** [comment]
Unfortunately I closed this issue too early - ARM builds still aren't fully supported.

This is because of native binaries needed in the image don't have prebuilt versions for ARM architectures and I'm having issues trying to compile them from within the Alpine Linux container.

I'll keep working on this and see if I can find a workaround.

**Comment by jonahsnider** [comment]
Docker images for ZWS are no longer being provided
