### ISSUE TITLE
Can create duplicate urls

### ISSUE THREAD

**Issue by CuteistFox** [zws-im/zws#748]
When i shortend the url of this github, i got `https://zws.im/󠁣󠁷󠁺󠁰󠁨󠁶󠁫` and `https://zws.im/󠁨󠁧󠁦󠁡󠁨󠁤󠁷` and they are not equal to each other. To prevent filling the db with duplicate entries(and making the urls longer), make it so that if you shorten already shortend url, it wont duplicate.

**Comment by jonahsnider** [comment]
This would allow for shorter URLs, and in fact this is what the original version of ZWS did. I later decided to remove that behavior, and create a unique URL every time.

No other URL shorteners implement that kind of shortened URL reuse, so I think users would find it confusing/unintuitive. It also makes checking URL stats difficult, since you can't be sure the stats you're looking at are from a URL you shared vs a URL someone had shortened previously.
